### ISSUE TITLE
Unable to Start the application at http://localhost:9090/FOX/fox/!LOGIN

### ISSUE THREAD

**Issue by adityasood** [Fivium/FOXopen#1]
Hi I am unable to start the service . I continuously get an error for creating Security file. Please help in this issues

**Comment by adityasood** [comment]
Hi I am unable to login into the FoxOpen portal http://localhost:9090/FOX/fox/fxo/LOGIN001L. This is really urgent any help will be appreciated

**Comment by Palmr** [comment]
Hi @adityasood 
This repository is just the app server code for FOX5 and the Oracle database code which is required for use is not yet fully open source, so unfortunately you won't be able to use this framework until then.

**Comment by asaadhoussam** [comment]
can i help you?
oky
let me to show how to create tablespaces!
